name: release_to_github_page

on:
  push:
    branches:
      - master
      - zz_dev
      - kk_dev
      - hn_dev
      - v66_dev
      - Kong_dev
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - run: npm install
 
      - name: Build
        run: npm run build2

      - name: Clone Page
        run: git clone https://github.com/${{ github.repository }}.git --branch dev_release --single-branch dev_release

      - name: Pack
        run: node pack_dev_release.js ${{ env.BRANCH_NAME }}
 
      - name: Page Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dev_release
          publish_branch: dev_release